// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package vm

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type VirtualMachine struct {
	pulumi.CustomResourceState

	// Whether to enable ACPI
	Acpi pulumi.BoolPtrOutput `pulumi:"acpi"`
	// The QEMU agent configuration
	Agent VirtualMachineAgentPtrOutput `pulumi:"agent"`
	// The audio devices
	AudioDevice VirtualMachineAudioDevicePtrOutput `pulumi:"audioDevice"`
	// The BIOS implementation
	Bios pulumi.StringPtrOutput `pulumi:"bios"`
	// The CDROM drive
	Cdrom VirtualMachineCdromPtrOutput `pulumi:"cdrom"`
	// The cloning configuration
	Clone VirtualMachineClonePtrOutput `pulumi:"clone"`
	// The CPU allocation
	Cpu VirtualMachineCpuPtrOutput `pulumi:"cpu"`
	// The description
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The disk devices
	Disks VirtualMachineDiskArrayOutput `pulumi:"disks"`
	// The cloud-init configuration
	Initialization VirtualMachineInitializationPtrOutput `pulumi:"initialization"`
	// The IPv4 addresses published by the QEMU agent
	Ipv4Addresses pulumi.StringArrayArrayOutput `pulumi:"ipv4Addresses"`
	// The IPv6 addresses published by the QEMU agent
	Ipv6Addresses pulumi.StringArrayArrayOutput `pulumi:"ipv6Addresses"`
	// The keyboard layout
	KeyboardLayout pulumi.StringPtrOutput `pulumi:"keyboardLayout"`
	// The MAC addresses for the network interfaces
	MacAddresses pulumi.StringArrayOutput `pulumi:"macAddresses"`
	// The memory allocation
	Memory VirtualMachineMemoryPtrOutput `pulumi:"memory"`
	// The name
	Name pulumi.StringOutput `pulumi:"name"`
	// The network devices
	NetworkDevices VirtualMachineNetworkDeviceArrayOutput `pulumi:"networkDevices"`
	// The network interface names published by the QEMU agent
	NetworkInterfaceNames pulumi.StringArrayOutput `pulumi:"networkInterfaceNames"`
	// The node name
	NodeName pulumi.StringOutput `pulumi:"nodeName"`
	// Start VM on Node boot
	OnBoot pulumi.BoolPtrOutput `pulumi:"onBoot"`
	// The operating system configuration
	OperatingSystem VirtualMachineOperatingSystemPtrOutput `pulumi:"operatingSystem"`
	// The ID of the pool to assign the virtual machine to
	PoolId pulumi.StringPtrOutput `pulumi:"poolId"`
	// Wether to reboot vm after creation
	Reboot pulumi.BoolPtrOutput `pulumi:"reboot"`
	// The serial devices
	SerialDevices VirtualMachineSerialDeviceArrayOutput `pulumi:"serialDevices"`
	// Whether to start the virtual machine
	Started pulumi.BoolPtrOutput `pulumi:"started"`
	// Whether to enable the USB tablet device
	TabletDevice pulumi.BoolPtrOutput `pulumi:"tabletDevice"`
	// Whether to create a template
	Template pulumi.BoolPtrOutput `pulumi:"template"`
	// The VGA configuration
	Vga VirtualMachineVgaPtrOutput `pulumi:"vga"`
	// The VM identifier
	VmId pulumi.IntPtrOutput `pulumi:"vmId"`
}

// NewVirtualMachine registers a new resource with the given unique name, arguments, and options.
func NewVirtualMachine(ctx *pulumi.Context,
	name string, args *VirtualMachineArgs, opts ...pulumi.ResourceOption) (*VirtualMachine, error) {
	if args == nil || args.NodeName == nil {
		return nil, errors.New("missing required argument 'NodeName'")
	}
	if args == nil {
		args = &VirtualMachineArgs{}
	}
	var resource VirtualMachine
	err := ctx.RegisterResource("proxmox:VM/virtualMachine:VirtualMachine", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetVirtualMachine gets an existing VirtualMachine resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetVirtualMachine(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *VirtualMachineState, opts ...pulumi.ResourceOption) (*VirtualMachine, error) {
	var resource VirtualMachine
	err := ctx.ReadResource("proxmox:VM/virtualMachine:VirtualMachine", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering VirtualMachine resources.
type virtualMachineState struct {
	// Whether to enable ACPI
	Acpi *bool `pulumi:"acpi"`
	// The QEMU agent configuration
	Agent *VirtualMachineAgent `pulumi:"agent"`
	// The audio devices
	AudioDevice *VirtualMachineAudioDevice `pulumi:"audioDevice"`
	// The BIOS implementation
	Bios *string `pulumi:"bios"`
	// The CDROM drive
	Cdrom *VirtualMachineCdrom `pulumi:"cdrom"`
	// The cloning configuration
	Clone *VirtualMachineClone `pulumi:"clone"`
	// The CPU allocation
	Cpu *VirtualMachineCpu `pulumi:"cpu"`
	// The description
	Description *string `pulumi:"description"`
	// The disk devices
	Disks []VirtualMachineDisk `pulumi:"disks"`
	// The cloud-init configuration
	Initialization *VirtualMachineInitialization `pulumi:"initialization"`
	// The IPv4 addresses published by the QEMU agent
	Ipv4Addresses [][]string `pulumi:"ipv4Addresses"`
	// The IPv6 addresses published by the QEMU agent
	Ipv6Addresses [][]string `pulumi:"ipv6Addresses"`
	// The keyboard layout
	KeyboardLayout *string `pulumi:"keyboardLayout"`
	// The MAC addresses for the network interfaces
	MacAddresses []string `pulumi:"macAddresses"`
	// The memory allocation
	Memory *VirtualMachineMemory `pulumi:"memory"`
	// The name
	Name *string `pulumi:"name"`
	// The network devices
	NetworkDevices []VirtualMachineNetworkDevice `pulumi:"networkDevices"`
	// The network interface names published by the QEMU agent
	NetworkInterfaceNames []string `pulumi:"networkInterfaceNames"`
	// The node name
	NodeName *string `pulumi:"nodeName"`
	// Start VM on Node boot
	OnBoot *bool `pulumi:"onBoot"`
	// The operating system configuration
	OperatingSystem *VirtualMachineOperatingSystem `pulumi:"operatingSystem"`
	// The ID of the pool to assign the virtual machine to
	PoolId *string `pulumi:"poolId"`
	// Wether to reboot vm after creation
	Reboot *bool `pulumi:"reboot"`
	// The serial devices
	SerialDevices []VirtualMachineSerialDevice `pulumi:"serialDevices"`
	// Whether to start the virtual machine
	Started *bool `pulumi:"started"`
	// Whether to enable the USB tablet device
	TabletDevice *bool `pulumi:"tabletDevice"`
	// Whether to create a template
	Template *bool `pulumi:"template"`
	// The VGA configuration
	Vga *VirtualMachineVga `pulumi:"vga"`
	// The VM identifier
	VmId *int `pulumi:"vmId"`
}

type VirtualMachineState struct {
	// Whether to enable ACPI
	Acpi pulumi.BoolPtrInput
	// The QEMU agent configuration
	Agent VirtualMachineAgentPtrInput
	// The audio devices
	AudioDevice VirtualMachineAudioDevicePtrInput
	// The BIOS implementation
	Bios pulumi.StringPtrInput
	// The CDROM drive
	Cdrom VirtualMachineCdromPtrInput
	// The cloning configuration
	Clone VirtualMachineClonePtrInput
	// The CPU allocation
	Cpu VirtualMachineCpuPtrInput
	// The description
	Description pulumi.StringPtrInput
	// The disk devices
	Disks VirtualMachineDiskArrayInput
	// The cloud-init configuration
	Initialization VirtualMachineInitializationPtrInput
	// The IPv4 addresses published by the QEMU agent
	Ipv4Addresses pulumi.StringArrayArrayInput
	// The IPv6 addresses published by the QEMU agent
	Ipv6Addresses pulumi.StringArrayArrayInput
	// The keyboard layout
	KeyboardLayout pulumi.StringPtrInput
	// The MAC addresses for the network interfaces
	MacAddresses pulumi.StringArrayInput
	// The memory allocation
	Memory VirtualMachineMemoryPtrInput
	// The name
	Name pulumi.StringPtrInput
	// The network devices
	NetworkDevices VirtualMachineNetworkDeviceArrayInput
	// The network interface names published by the QEMU agent
	NetworkInterfaceNames pulumi.StringArrayInput
	// The node name
	NodeName pulumi.StringPtrInput
	// Start VM on Node boot
	OnBoot pulumi.BoolPtrInput
	// The operating system configuration
	OperatingSystem VirtualMachineOperatingSystemPtrInput
	// The ID of the pool to assign the virtual machine to
	PoolId pulumi.StringPtrInput
	// Wether to reboot vm after creation
	Reboot pulumi.BoolPtrInput
	// The serial devices
	SerialDevices VirtualMachineSerialDeviceArrayInput
	// Whether to start the virtual machine
	Started pulumi.BoolPtrInput
	// Whether to enable the USB tablet device
	TabletDevice pulumi.BoolPtrInput
	// Whether to create a template
	Template pulumi.BoolPtrInput
	// The VGA configuration
	Vga VirtualMachineVgaPtrInput
	// The VM identifier
	VmId pulumi.IntPtrInput
}

func (VirtualMachineState) ElementType() reflect.Type {
	return reflect.TypeOf((*virtualMachineState)(nil)).Elem()
}

type virtualMachineArgs struct {
	// Whether to enable ACPI
	Acpi *bool `pulumi:"acpi"`
	// The QEMU agent configuration
	Agent *VirtualMachineAgent `pulumi:"agent"`
	// The audio devices
	AudioDevice *VirtualMachineAudioDevice `pulumi:"audioDevice"`
	// The BIOS implementation
	Bios *string `pulumi:"bios"`
	// The CDROM drive
	Cdrom *VirtualMachineCdrom `pulumi:"cdrom"`
	// The cloning configuration
	Clone *VirtualMachineClone `pulumi:"clone"`
	// The CPU allocation
	Cpu *VirtualMachineCpu `pulumi:"cpu"`
	// The description
	Description *string `pulumi:"description"`
	// The disk devices
	Disks []VirtualMachineDisk `pulumi:"disks"`
	// The cloud-init configuration
	Initialization *VirtualMachineInitialization `pulumi:"initialization"`
	// The keyboard layout
	KeyboardLayout *string `pulumi:"keyboardLayout"`
	// The memory allocation
	Memory *VirtualMachineMemory `pulumi:"memory"`
	// The name
	Name *string `pulumi:"name"`
	// The network devices
	NetworkDevices []VirtualMachineNetworkDevice `pulumi:"networkDevices"`
	// The node name
	NodeName string `pulumi:"nodeName"`
	// Start VM on Node boot
	OnBoot *bool `pulumi:"onBoot"`
	// The operating system configuration
	OperatingSystem *VirtualMachineOperatingSystem `pulumi:"operatingSystem"`
	// The ID of the pool to assign the virtual machine to
	PoolId *string `pulumi:"poolId"`
	// Wether to reboot vm after creation
	Reboot *bool `pulumi:"reboot"`
	// The serial devices
	SerialDevices []VirtualMachineSerialDevice `pulumi:"serialDevices"`
	// Whether to start the virtual machine
	Started *bool `pulumi:"started"`
	// Whether to enable the USB tablet device
	TabletDevice *bool `pulumi:"tabletDevice"`
	// Whether to create a template
	Template *bool `pulumi:"template"`
	// The VGA configuration
	Vga *VirtualMachineVga `pulumi:"vga"`
	// The VM identifier
	VmId *int `pulumi:"vmId"`
}

// The set of arguments for constructing a VirtualMachine resource.
type VirtualMachineArgs struct {
	// Whether to enable ACPI
	Acpi pulumi.BoolPtrInput
	// The QEMU agent configuration
	Agent VirtualMachineAgentPtrInput
	// The audio devices
	AudioDevice VirtualMachineAudioDevicePtrInput
	// The BIOS implementation
	Bios pulumi.StringPtrInput
	// The CDROM drive
	Cdrom VirtualMachineCdromPtrInput
	// The cloning configuration
	Clone VirtualMachineClonePtrInput
	// The CPU allocation
	Cpu VirtualMachineCpuPtrInput
	// The description
	Description pulumi.StringPtrInput
	// The disk devices
	Disks VirtualMachineDiskArrayInput
	// The cloud-init configuration
	Initialization VirtualMachineInitializationPtrInput
	// The keyboard layout
	KeyboardLayout pulumi.StringPtrInput
	// The memory allocation
	Memory VirtualMachineMemoryPtrInput
	// The name
	Name pulumi.StringPtrInput
	// The network devices
	NetworkDevices VirtualMachineNetworkDeviceArrayInput
	// The node name
	NodeName pulumi.StringInput
	// Start VM on Node boot
	OnBoot pulumi.BoolPtrInput
	// The operating system configuration
	OperatingSystem VirtualMachineOperatingSystemPtrInput
	// The ID of the pool to assign the virtual machine to
	PoolId pulumi.StringPtrInput
	// Wether to reboot vm after creation
	Reboot pulumi.BoolPtrInput
	// The serial devices
	SerialDevices VirtualMachineSerialDeviceArrayInput
	// Whether to start the virtual machine
	Started pulumi.BoolPtrInput
	// Whether to enable the USB tablet device
	TabletDevice pulumi.BoolPtrInput
	// Whether to create a template
	Template pulumi.BoolPtrInput
	// The VGA configuration
	Vga VirtualMachineVgaPtrInput
	// The VM identifier
	VmId pulumi.IntPtrInput
}

func (VirtualMachineArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*virtualMachineArgs)(nil)).Elem()
}
