// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmox.VM.Outputs
{

    [OutputType]
    public sealed class VirtualMachineInitialization
    {
        public readonly string? DatastoreId;
        public readonly Outputs.VirtualMachineInitializationDns? Dns;
        public readonly ImmutableArray<Outputs.VirtualMachineInitializationIpConfig> IpConfigs;
        public readonly Outputs.VirtualMachineInitializationUserAccount? UserAccount;
        public readonly string? UserDataFileId;

        [OutputConstructor]
        private VirtualMachineInitialization(
            string? datastoreId,

            Outputs.VirtualMachineInitializationDns? dns,

            ImmutableArray<Outputs.VirtualMachineInitializationIpConfig> ipConfigs,

            Outputs.VirtualMachineInitializationUserAccount? userAccount,

            string? userDataFileId)
        {
            DatastoreId = datastoreId;
            Dns = dns;
            IpConfigs = ipConfigs;
            UserAccount = userAccount;
            UserDataFileId = userDataFileId;
        }
    }
}
