// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getDNS(args: GetDNSArgs, opts?: pulumi.InvokeOptions): Promise<GetDNSResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("proxmox:System/getDNS:getDNS", {
        "nodeName": args.nodeName,
    }, opts);
}

/**
 * A collection of arguments for invoking getDNS.
 */
export interface GetDNSArgs {
    readonly nodeName: string;
}

/**
 * A collection of values returned by getDNS.
 */
export interface GetDNSResult {
    readonly domain: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly nodeName: string;
    readonly servers: string[];
}
