// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System.Collections.Immutable;

namespace Pulumi.Proxmox
{
    public static class Config
    {
        private static readonly Pulumi.Config __config = new Pulumi.Config("proxmox");
        public static Pulumi.Proxmox.Config.Types.VirtualEnvironment? VirtualEnvironment { get; set; } = __config.GetObject<Pulumi.Proxmox.Config.Types.VirtualEnvironment>("virtualEnvironment");

        public static class Types
        {

             public class VirtualEnvironment
             {
                public string? Endpoint { get; set; } = null!;
                public bool? Insecure { get; set; }
                public string? Otp { get; set; } = null!;
                public string? Password { get; set; } = null!;
                public string? Username { get; set; } = null!;
            }
        }
    }
}
