// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package storage

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func GetDatastores(ctx *pulumi.Context, args *GetDatastoresArgs, opts ...pulumi.InvokeOption) (*GetDatastoresResult, error) {
	var rv GetDatastoresResult
	err := ctx.Invoke("proxmox:Storage/getDatastores:getDatastores", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDatastores.
type GetDatastoresArgs struct {
	NodeName string `pulumi:"nodeName"`
}

// A collection of values returned by getDatastores.
type GetDatastoresResult struct {
	Actives      []bool     `pulumi:"actives"`
	ContentTypes [][]string `pulumi:"contentTypes"`
	DatastoreIds []string   `pulumi:"datastoreIds"`
	Enableds     []bool     `pulumi:"enableds"`
	// The provider-assigned unique ID for this managed resource.
	Id              string `pulumi:"id"`
	NodeName        string `pulumi:"nodeName"`
	Shareds         []bool `pulumi:"shareds"`
	SpaceAvailables []int  `pulumi:"spaceAvailables"`
	SpaceTotals     []int  `pulumi:"spaceTotals"`
	SpaceUseds      []int  `pulumi:"spaceUseds"`
	Types           []int  `pulumi:"types"`
}
