// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package proxmox

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type ProviderVirtualEnvironment struct {
	Endpoint *string `pulumi:"endpoint"`
	Insecure *bool   `pulumi:"insecure"`
	Otp      *string `pulumi:"otp"`
	Password *string `pulumi:"password"`
	Username *string `pulumi:"username"`
}

// ProviderVirtualEnvironmentInput is an input type that accepts ProviderVirtualEnvironmentArgs and ProviderVirtualEnvironmentOutput values.
// You can construct a concrete instance of `ProviderVirtualEnvironmentInput` via:
//
//          ProviderVirtualEnvironmentArgs{...}
type ProviderVirtualEnvironmentInput interface {
	pulumi.Input

	ToProviderVirtualEnvironmentOutput() ProviderVirtualEnvironmentOutput
	ToProviderVirtualEnvironmentOutputWithContext(context.Context) ProviderVirtualEnvironmentOutput
}

type ProviderVirtualEnvironmentArgs struct {
	Endpoint pulumi.StringPtrInput `pulumi:"endpoint"`
	Insecure pulumi.BoolPtrInput   `pulumi:"insecure"`
	Otp      pulumi.StringPtrInput `pulumi:"otp"`
	Password pulumi.StringPtrInput `pulumi:"password"`
	Username pulumi.StringPtrInput `pulumi:"username"`
}

func (ProviderVirtualEnvironmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderVirtualEnvironment)(nil)).Elem()
}

func (i ProviderVirtualEnvironmentArgs) ToProviderVirtualEnvironmentOutput() ProviderVirtualEnvironmentOutput {
	return i.ToProviderVirtualEnvironmentOutputWithContext(context.Background())
}

func (i ProviderVirtualEnvironmentArgs) ToProviderVirtualEnvironmentOutputWithContext(ctx context.Context) ProviderVirtualEnvironmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderVirtualEnvironmentOutput)
}

func (i ProviderVirtualEnvironmentArgs) ToProviderVirtualEnvironmentPtrOutput() ProviderVirtualEnvironmentPtrOutput {
	return i.ToProviderVirtualEnvironmentPtrOutputWithContext(context.Background())
}

func (i ProviderVirtualEnvironmentArgs) ToProviderVirtualEnvironmentPtrOutputWithContext(ctx context.Context) ProviderVirtualEnvironmentPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderVirtualEnvironmentOutput).ToProviderVirtualEnvironmentPtrOutputWithContext(ctx)
}

// ProviderVirtualEnvironmentPtrInput is an input type that accepts ProviderVirtualEnvironmentArgs, ProviderVirtualEnvironmentPtr and ProviderVirtualEnvironmentPtrOutput values.
// You can construct a concrete instance of `ProviderVirtualEnvironmentPtrInput` via:
//
//          ProviderVirtualEnvironmentArgs{...}
//
//  or:
//
//          nil
type ProviderVirtualEnvironmentPtrInput interface {
	pulumi.Input

	ToProviderVirtualEnvironmentPtrOutput() ProviderVirtualEnvironmentPtrOutput
	ToProviderVirtualEnvironmentPtrOutputWithContext(context.Context) ProviderVirtualEnvironmentPtrOutput
}

type providerVirtualEnvironmentPtrType ProviderVirtualEnvironmentArgs

func ProviderVirtualEnvironmentPtr(v *ProviderVirtualEnvironmentArgs) ProviderVirtualEnvironmentPtrInput {
	return (*providerVirtualEnvironmentPtrType)(v)
}

func (*providerVirtualEnvironmentPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderVirtualEnvironment)(nil)).Elem()
}

func (i *providerVirtualEnvironmentPtrType) ToProviderVirtualEnvironmentPtrOutput() ProviderVirtualEnvironmentPtrOutput {
	return i.ToProviderVirtualEnvironmentPtrOutputWithContext(context.Background())
}

func (i *providerVirtualEnvironmentPtrType) ToProviderVirtualEnvironmentPtrOutputWithContext(ctx context.Context) ProviderVirtualEnvironmentPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderVirtualEnvironmentPtrOutput)
}

type ProviderVirtualEnvironmentOutput struct{ *pulumi.OutputState }

func (ProviderVirtualEnvironmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ProviderVirtualEnvironment)(nil)).Elem()
}

func (o ProviderVirtualEnvironmentOutput) ToProviderVirtualEnvironmentOutput() ProviderVirtualEnvironmentOutput {
	return o
}

func (o ProviderVirtualEnvironmentOutput) ToProviderVirtualEnvironmentOutputWithContext(ctx context.Context) ProviderVirtualEnvironmentOutput {
	return o
}

func (o ProviderVirtualEnvironmentOutput) ToProviderVirtualEnvironmentPtrOutput() ProviderVirtualEnvironmentPtrOutput {
	return o.ToProviderVirtualEnvironmentPtrOutputWithContext(context.Background())
}

func (o ProviderVirtualEnvironmentOutput) ToProviderVirtualEnvironmentPtrOutputWithContext(ctx context.Context) ProviderVirtualEnvironmentPtrOutput {
	return o.ApplyT(func(v ProviderVirtualEnvironment) *ProviderVirtualEnvironment {
		return &v
	}).(ProviderVirtualEnvironmentPtrOutput)
}
func (o ProviderVirtualEnvironmentOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ProviderVirtualEnvironment) *string { return v.Endpoint }).(pulumi.StringPtrOutput)
}

func (o ProviderVirtualEnvironmentOutput) Insecure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v ProviderVirtualEnvironment) *bool { return v.Insecure }).(pulumi.BoolPtrOutput)
}

func (o ProviderVirtualEnvironmentOutput) Otp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ProviderVirtualEnvironment) *string { return v.Otp }).(pulumi.StringPtrOutput)
}

func (o ProviderVirtualEnvironmentOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ProviderVirtualEnvironment) *string { return v.Password }).(pulumi.StringPtrOutput)
}

func (o ProviderVirtualEnvironmentOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ProviderVirtualEnvironment) *string { return v.Username }).(pulumi.StringPtrOutput)
}

type ProviderVirtualEnvironmentPtrOutput struct{ *pulumi.OutputState }

func (ProviderVirtualEnvironmentPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ProviderVirtualEnvironment)(nil)).Elem()
}

func (o ProviderVirtualEnvironmentPtrOutput) ToProviderVirtualEnvironmentPtrOutput() ProviderVirtualEnvironmentPtrOutput {
	return o
}

func (o ProviderVirtualEnvironmentPtrOutput) ToProviderVirtualEnvironmentPtrOutputWithContext(ctx context.Context) ProviderVirtualEnvironmentPtrOutput {
	return o
}

func (o ProviderVirtualEnvironmentPtrOutput) Elem() ProviderVirtualEnvironmentOutput {
	return o.ApplyT(func(v *ProviderVirtualEnvironment) ProviderVirtualEnvironment { return *v }).(ProviderVirtualEnvironmentOutput)
}

func (o ProviderVirtualEnvironmentPtrOutput) Endpoint() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderVirtualEnvironment) *string {
		if v == nil {
			return nil
		}
		return v.Endpoint
	}).(pulumi.StringPtrOutput)
}

func (o ProviderVirtualEnvironmentPtrOutput) Insecure() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ProviderVirtualEnvironment) *bool {
		if v == nil {
			return nil
		}
		return v.Insecure
	}).(pulumi.BoolPtrOutput)
}

func (o ProviderVirtualEnvironmentPtrOutput) Otp() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderVirtualEnvironment) *string {
		if v == nil {
			return nil
		}
		return v.Otp
	}).(pulumi.StringPtrOutput)
}

func (o ProviderVirtualEnvironmentPtrOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderVirtualEnvironment) *string {
		if v == nil {
			return nil
		}
		return v.Password
	}).(pulumi.StringPtrOutput)
}

func (o ProviderVirtualEnvironmentPtrOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ProviderVirtualEnvironment) *string {
		if v == nil {
			return nil
		}
		return v.Username
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(ProviderVirtualEnvironmentOutput{})
	pulumi.RegisterOutputType(ProviderVirtualEnvironmentPtrOutput{})
}
