// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getUser(args: GetUserArgs, opts?: pulumi.InvokeOptions): Promise<GetUserResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("proxmox:Permission/getUser:getUser", {
        "userId": args.userId,
    }, opts);
}

/**
 * A collection of arguments for invoking getUser.
 */
export interface GetUserArgs {
    readonly userId: string;
}

/**
 * A collection of values returned by getUser.
 */
export interface GetUserResult {
    readonly acls: outputs.Permission.GetUserAcl[];
    readonly comment: string;
    readonly email: string;
    readonly enabled: boolean;
    readonly expirationDate: string;
    readonly firstName: string;
    readonly groups: string[];
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly keys: string;
    readonly lastName: string;
    readonly userId: string;
}
