# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

# Export this package's modules as members:
from .certifi import *
from .dns import *
from .get_dns import *
from .get_hosts import *
from .get_time import *
from .hosts import *
from .time import *
from ._inputs import *
from . import outputs
