// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package system

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupDNS(ctx *pulumi.Context, args *LookupDNSArgs, opts ...pulumi.InvokeOption) (*LookupDNSResult, error) {
	var rv LookupDNSResult
	err := ctx.Invoke("proxmox:System/getDNS:getDNS", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDNS.
type LookupDNSArgs struct {
	NodeName string `pulumi:"nodeName"`
}

// A collection of values returned by getDNS.
type LookupDNSResult struct {
	Domain string `pulumi:"domain"`
	// The provider-assigned unique ID for this managed resource.
	Id       string   `pulumi:"id"`
	NodeName string   `pulumi:"nodeName"`
	Servers  []string `pulumi:"servers"`
}
