// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package system

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupHosts(ctx *pulumi.Context, args *LookupHostsArgs, opts ...pulumi.InvokeOption) (*LookupHostsResult, error) {
	var rv LookupHostsResult
	err := ctx.Invoke("proxmox:System/getHosts:getHosts", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getHosts.
type LookupHostsArgs struct {
	NodeName string `pulumi:"nodeName"`
}

// A collection of values returned by getHosts.
type LookupHostsResult struct {
	Addresses []string        `pulumi:"addresses"`
	Digest    string          `pulumi:"digest"`
	Entries   []GetHostsEntry `pulumi:"entries"`
	Hostnames [][]string      `pulumi:"hostnames"`
	// The provider-assigned unique ID for this managed resource.
	Id       string `pulumi:"id"`
	NodeName string `pulumi:"nodeName"`
}
