// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package system

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupTime(ctx *pulumi.Context, args *LookupTimeArgs, opts ...pulumi.InvokeOption) (*LookupTimeResult, error) {
	var rv LookupTimeResult
	err := ctx.Invoke("proxmox:System/getTime:getTime", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTime.
type LookupTimeArgs struct {
	NodeName string `pulumi:"nodeName"`
}

// A collection of values returned by getTime.
type LookupTimeResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	LocalTime string `pulumi:"localTime"`
	NodeName  string `pulumi:"nodeName"`
	TimeZone  string `pulumi:"timeZone"`
	UtcTime   string `pulumi:"utcTime"`
}
