// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package system

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type Hosts struct {
	pulumi.CustomResourceState

	// The addresses
	Addresses pulumi.StringArrayOutput `pulumi:"addresses"`
	// The SHA1 digest
	Digest pulumi.StringOutput `pulumi:"digest"`
	// The host entries
	Entries HostsEntryArrayOutput `pulumi:"entries"`
	// The hostnames
	Hostnames pulumi.StringArrayArrayOutput `pulumi:"hostnames"`
	// The node name
	NodeName pulumi.StringOutput `pulumi:"nodeName"`
}

// NewHosts registers a new resource with the given unique name, arguments, and options.
func NewHosts(ctx *pulumi.Context,
	name string, args *HostsArgs, opts ...pulumi.ResourceOption) (*Hosts, error) {
	if args == nil || args.Entries == nil {
		return nil, errors.New("missing required argument 'Entries'")
	}
	if args == nil || args.NodeName == nil {
		return nil, errors.New("missing required argument 'NodeName'")
	}
	if args == nil {
		args = &HostsArgs{}
	}
	var resource Hosts
	err := ctx.RegisterResource("proxmox:System/hosts:Hosts", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHosts gets an existing Hosts resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHosts(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HostsState, opts ...pulumi.ResourceOption) (*Hosts, error) {
	var resource Hosts
	err := ctx.ReadResource("proxmox:System/hosts:Hosts", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Hosts resources.
type hostsState struct {
	// The addresses
	Addresses []string `pulumi:"addresses"`
	// The SHA1 digest
	Digest *string `pulumi:"digest"`
	// The host entries
	Entries []HostsEntry `pulumi:"entries"`
	// The hostnames
	Hostnames [][]string `pulumi:"hostnames"`
	// The node name
	NodeName *string `pulumi:"nodeName"`
}

type HostsState struct {
	// The addresses
	Addresses pulumi.StringArrayInput
	// The SHA1 digest
	Digest pulumi.StringPtrInput
	// The host entries
	Entries HostsEntryArrayInput
	// The hostnames
	Hostnames pulumi.StringArrayArrayInput
	// The node name
	NodeName pulumi.StringPtrInput
}

func (HostsState) ElementType() reflect.Type {
	return reflect.TypeOf((*hostsState)(nil)).Elem()
}

type hostsArgs struct {
	// The host entries
	Entries []HostsEntry `pulumi:"entries"`
	// The node name
	NodeName string `pulumi:"nodeName"`
}

// The set of arguments for constructing a Hosts resource.
type HostsArgs struct {
	// The host entries
	Entries HostsEntryArrayInput
	// The node name
	NodeName pulumi.StringInput
}

func (HostsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hostsArgs)(nil)).Elem()
}
