// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package permission

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupGroup(ctx *pulumi.Context, args *LookupGroupArgs, opts ...pulumi.InvokeOption) (*LookupGroupResult, error) {
	var rv LookupGroupResult
	err := ctx.Invoke("proxmox:Permission/getGroup:getGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGroup.
type LookupGroupArgs struct {
	GroupId string `pulumi:"groupId"`
}

// A collection of values returned by getGroup.
type LookupGroupResult struct {
	Acls    []GetGroupAcl `pulumi:"acls"`
	Comment string        `pulumi:"comment"`
	GroupId string        `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id      string   `pulumi:"id"`
	Members []string `pulumi:"members"`
}
