// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package permission

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupPool(ctx *pulumi.Context, args *LookupPoolArgs, opts ...pulumi.InvokeOption) (*LookupPoolResult, error) {
	var rv LookupPoolResult
	err := ctx.Invoke("proxmox:Permission/getPool:getPool", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPool.
type LookupPoolArgs struct {
	PoolId string `pulumi:"poolId"`
}

// A collection of values returned by getPool.
type LookupPoolResult struct {
	Comment string `pulumi:"comment"`
	// The provider-assigned unique ID for this managed resource.
	Id      string          `pulumi:"id"`
	Members []GetPoolMember `pulumi:"members"`
	PoolId  string          `pulumi:"poolId"`
}
