// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package permission

import (
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

func LookupUser(ctx *pulumi.Context, args *LookupUserArgs, opts ...pulumi.InvokeOption) (*LookupUserResult, error) {
	var rv LookupUserResult
	err := ctx.Invoke("proxmox:Permission/getUser:getUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUser.
type LookupUserArgs struct {
	UserId string `pulumi:"userId"`
}

// A collection of values returned by getUser.
type LookupUserResult struct {
	Acls           []GetUserAcl `pulumi:"acls"`
	Comment        string       `pulumi:"comment"`
	Email          string       `pulumi:"email"`
	Enabled        bool         `pulumi:"enabled"`
	ExpirationDate string       `pulumi:"expirationDate"`
	FirstName      string       `pulumi:"firstName"`
	Groups         []string     `pulumi:"groups"`
	// The provider-assigned unique ID for this managed resource.
	Id       string `pulumi:"id"`
	Keys     string `pulumi:"keys"`
	LastName string `pulumi:"lastName"`
	UserId   string `pulumi:"userId"`
}
