// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package permission

import (
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v2/go/pulumi"
)

type Group struct {
	pulumi.CustomResourceState

	// The access control list
	Acls GroupAclArrayOutput `pulumi:"acls"`
	// The group comment
	Comment pulumi.StringPtrOutput `pulumi:"comment"`
	// The group id
	GroupId pulumi.StringOutput `pulumi:"groupId"`
	// The group members
	Members pulumi.StringArrayOutput `pulumi:"members"`
}

// NewGroup registers a new resource with the given unique name, arguments, and options.
func NewGroup(ctx *pulumi.Context,
	name string, args *GroupArgs, opts ...pulumi.ResourceOption) (*Group, error) {
	if args == nil || args.GroupId == nil {
		return nil, errors.New("missing required argument 'GroupId'")
	}
	if args == nil {
		args = &GroupArgs{}
	}
	var resource Group
	err := ctx.RegisterResource("proxmox:Permission/group:Group", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetGroup gets an existing Group resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *GroupState, opts ...pulumi.ResourceOption) (*Group, error) {
	var resource Group
	err := ctx.ReadResource("proxmox:Permission/group:Group", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Group resources.
type groupState struct {
	// The access control list
	Acls []GroupAcl `pulumi:"acls"`
	// The group comment
	Comment *string `pulumi:"comment"`
	// The group id
	GroupId *string `pulumi:"groupId"`
	// The group members
	Members []string `pulumi:"members"`
}

type GroupState struct {
	// The access control list
	Acls GroupAclArrayInput
	// The group comment
	Comment pulumi.StringPtrInput
	// The group id
	GroupId pulumi.StringPtrInput
	// The group members
	Members pulumi.StringArrayInput
}

func (GroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*groupState)(nil)).Elem()
}

type groupArgs struct {
	// The access control list
	Acls []GroupAcl `pulumi:"acls"`
	// The group comment
	Comment *string `pulumi:"comment"`
	// The group id
	GroupId string `pulumi:"groupId"`
}

// The set of arguments for constructing a Group resource.
type GroupArgs struct {
	// The access control list
	Acls GroupAclArrayInput
	// The group comment
	Comment pulumi.StringPtrInput
	// The group id
	GroupId pulumi.StringInput
}

func (GroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*groupArgs)(nil)).Elem()
}
