// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Proxmox.Permission
{
    public static class GetPools
    {
        public static Task<GetPoolsResult> InvokeAsync(InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetPoolsResult>("proxmox:Permission/getPools:getPools", InvokeArgs.Empty, options.WithVersion());
    }


    [OutputType]
    public sealed class GetPoolsResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly ImmutableArray<string> PoolIds;

        [OutputConstructor]
        private GetPoolsResult(
            string id,

            ImmutableArray<string> poolIds)
        {
            Id = id;
            PoolIds = poolIds;
        }
    }
}
