// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getClusterAlias(args: GetClusterAliasArgs, opts?: pulumi.InvokeOptions): Promise<GetClusterAliasResult> {
    if (!opts) {
        opts = {}
    }

    if (!opts.version) {
        opts.version = utilities.getVersion();
    }
    return pulumi.runtime.invoke("proxmox:index/getClusterAlias:getClusterAlias", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getClusterAlias.
 */
export interface GetClusterAliasArgs {
    readonly name: string;
}

/**
 * A collection of values returned by getClusterAlias.
 */
export interface GetClusterAliasResult {
    readonly cidr: string;
    readonly comment: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
}
